# Generated by Django 2.0 on 2018-09-30 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TenderSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('tender_newspaper_id', models.CharField(blank=True, max_length=50)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_duplicated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('image_path', models.FileField(upload_to='snippets/')),
                ('tender_text', models.CharField(blank=True, max_length=200)),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Category')),
                ('publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Publisher')),
            ],
        ),
    ]
