# Generated by Django 2.0 on 2018-10-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendersnippet',
            name='title',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
