# Generated by Django 2.0 on 2018-10-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20181001_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendersnippet',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tendersnippet',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
