# Generated by Django 2.0 on 2018-10-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20181001_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendersnippet',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Publisher'),
        ),
    ]
