# Generated by Django 2.0 on 2018-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20181001_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendersnippet',
            name='image_path',
            field=models.FileField(upload_to='tenders_images/'),
        ),
    ]
