# Generated by Django 2.0 on 2018-10-09 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20181001_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('publish_date', models.DateField()),
                ('file', models.FileField(upload_to='', verbose_name='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to='', verbose_name='pages/')),
                ('newspaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Newspaper')),
            ],
        ),
        migrations.RenameField(
            model_name='tendersnippet',
            old_name='image_path',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='tendersnippet',
            old_name='is_accepted',
            new_name='is_republished',
        ),
        migrations.RenameField(
            model_name='tendersnippet',
            old_name='is_duplicated',
            new_name='is_tender',
        ),
        migrations.RenameField(
            model_name='tendersnippet',
            old_name='tender_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='tendersnippet',
            name='tender_newspaper_id',
        ),
        migrations.AlterField(
            model_name='tendersnippet',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Publisher'),
        ),
        migrations.AlterField(
            model_name='tendersnippet',
            name='title',
            field=models.CharField(choices=[('ADDUSTOUR', 'addustour'), ('ALRAI', 'alrai')], max_length=50),
        ),
        migrations.AddField(
            model_name='tendersnippet',
            name='newspaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Newspaper'),
        ),
    ]
