# Generated by Django 2.0 on 2018-10-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_newspaper_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
