# Generated by Django 2.0 on 2018-10-10 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0012_auto_20181009_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('extract_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('is_tender', models.BooleanField(default=False)),
                ('is_republished', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to='tenders_images/')),
                ('text', models.CharField(blank=True, max_length=200)),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='tendersnippet',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='tendersnippet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tendersnippet',
            name='newspaper',
        ),
        migrations.RemoveField(
            model_name='tendersnippet',
            name='publisher',
        ),
        migrations.AddField(
            model_name='newspaperpage',
            name='has_rectanges',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspaperpage',
            name='has_tenders',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(blank=True, choices=[('ADDUSTOUR', 'addustour'), ('ALRAI', 'alrai')], max_length=50),
        ),
        migrations.DeleteModel(
            name='TenderSnippet',
        ),
        migrations.AddField(
            model_name='snippet',
            name='newspaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Newspaper'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Publisher'),
        ),
    ]
