# Generated by Django 2.0 on 2018-10-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20181010_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='file',
            field=models.FileField(unique=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='newspaperpage',
            name='has_rectanges',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newspaperpage',
            name='has_tenders',
            field=models.BooleanField(default=False),
        ),
    ]
