# Generated by Django 2.0 on 2018-10-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20181010_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='coordinates',
        ),
    ]
