# Generated by Django 2.0 on 2018-10-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_remove_snippet_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.NewspaperPage'),
        ),
    ]
