# Generated by Django 2.0 on 2018-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_snippet_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaperpage',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
