# Generated by Django 2.0 on 2018-10-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_newspaperpage_is_extracted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaperpage',
            old_name='has_rectanges',
            new_name='has_rectangles',
        ),
    ]
