# Generated by Django 2.0 on 2018-10-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20181011_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='bw_rate',
            field=models.IntegerField(default=0),
        ),
    ]
