# Generated by Django 2.0 on 2018-10-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_snippet_bw_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='suggest_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_category', to='catalogue.Category'),
        ),
    ]
