# Generated by Django 2.0 on 2018-10-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_snippet_suggest_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='suggest_category',
            new_name='suggested_category',
        ),
    ]
