# Generated by Django 2.0 on 2018-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20181027_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='file',
            field=models.FileField(unique=True, upload_to='newspaper_pdfs/'),
        ),
    ]
