# Generated by Django 2.0 on 2018-10-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20181027_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='file',
            field=models.FileField(upload_to='newspaper_pdfs/'),
        ),
    ]
