# Generated by Django 2.0 on 2018-10-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20181027_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaperpage',
            name='newspaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Newspaper'),
        ),
    ]
