# Generated by Django 2.0 on 2018-10-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20181027_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaperpage',
            old_name='has_rectangles',
            new_name='has_snippets',
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='file',
            field=models.FileField(unique=True, upload_to='newspapers_pdfs/'),
        ),
        migrations.AlterField(
            model_name='newspaperpage',
            name='image',
            field=models.FileField(upload_to='newspapers_pages/'),
        ),
    ]
