# Generated by Django 2.0 on 2018-10-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_newspaper_is_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_find_tenders',
            field=models.BooleanField(default=False),
        ),
    ]
