# Generated by Django 2.0 on 2018-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_snippet_is_find_tenders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='is_find_tenders',
            new_name='is_auction',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='is_find_tenders',
            field=models.BooleanField(default=False),
        ),
    ]
