# Generated by Django 2.0 on 2018-10-31 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20181028_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='newspaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Newspaper'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.NewspaperPage'),
        ),
    ]
