# Generated by Django 2.0 on 2018-10-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20181031_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='tenders_images/'),
        ),
    ]
