# Generated by Django 2.0 on 2018-11-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_auto_20181031_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
