# Generated by Django 2.0 on 2018-11-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20181101_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
