# Generated by Django 2.0 on 2018-11-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_a_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b',
            name='aes',
        ),
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='B',
        ),
    ]
