# Generated by Django 2.0 on 2018-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20181119_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_ocred',
            field=models.BooleanField(default=False),
        ),
    ]
