# Generated by Django 2.0 on 2018-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20181119_1655'),
        ('authentication', '0002_auto_20181101_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='snippets',
            field=models.ManyToManyField(to='catalogue.Snippet'),
        ),
    ]
