# Generated by Django 2.0 on 2018-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20181119_1655'),
        ('authentication', '0003_userprofile_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(to='catalogue.Category'),
        ),
    ]
